Start of Zephyr work-q support
zephyrproject-rtos/zephyr-lang-rust pull request #45
Opened 2024-12-20 22:39 UTC by d3zd3z

This is some basic playing with Zephyr work queues, eventually with a goal of supporting both direct use of work queues as well as Futures.

This basic version is able to run a simple async Future that can use a 'sleep' function.

2025-01-10 03:42 UTC, theotherjimmy requested changes
nits and requests for unsafe docs, mostly.

2025-01-10 03:42 UTC, theotherjimmy commented on zephyr/src/work.rs
> +//! let main_worker = Box::new(j
Extraneous `j`  (do you perhaps use vim ;) 

doc tests might catch this, if that's possible.

2025-01-10 03:42 UTC, theotherjimmy commented on zephyr/src/work.rs
> +/// it are relatively fast.  In this case, `jnsert` and `get` on the SimpleTls are reasonably fast.
s/jnsert/insert

2025-01-10 03:42 UTC, theotherjimmy commented on zephyr/src/work.rs
> +    pub fn new() -> Result<Signal, Infallible> {
Did I miss why this must be a `Result<Self, Infallible>`? It seems like `Self` would also work here.

2025-01-10 03:42 UTC, theotherjimmy commented on zephyr/src/work/futures.rs
> +    pub unsafe fn add_semaphore<'a>(&'a mut self, sem: &'a Semaphore) {
It's not clear from the documentation what safety invariant the caller must uphold.

2025-01-10 03:42 UTC, theotherjimmy commented on zephyr/src/work/futures.rs
> +    pub unsafe fn add_signal<'a>(&'a mut self, signal: &'a Signal) {
Document caller requirements.

2025-01-10 03:42 UTC, theotherjimmy commented on zephyr/src/work/futures.rs
> +    pub unsafe fn add_queue<'a>(&'a mut self, queue: &'a Queue) {
here too.

2025-01-10 03:42 UTC, theotherjimmy commented on zephyr/src/work.rs
> +///
close the code block.

2025-01-14 17:11 UTC, d3zd3z commented on zephyr/src/kio.rs
> +/// The main use for this is to allow work threads to use `Rc` and `Rc<RefCell<T>>` within async
I believe the Send of the output is independent of the Send of the Future itself. At least if I did it right, the async wait on the Answer should properly have Send based on the output.

2025-01-16 22:39 UTC, d3zd3z commented on zephyr/src/work.rs
> +//! let main_worker = Box::new(j
Eventually, perhaps. I'm looking into how regular tests might be possible (at least with nightly) as we can provide our own test runner. The doc tests are generally just compiled though, so that might not be as difficult, but is still likely to require nightly.

2025-01-16 23:08 UTC, theotherjimmy commented on zephyr/src/work.rs
> +//! let main_worker = Box::new(j
I think doc tests are on stable, and should work during `cargo test`.

2025-02-11 17:53 UTC, teburd approved these changes
It's a fairly large PR so I can't say I looked *deeply* at this, but the samples look fine to me and the async bits seem ok, I wouldn't label this kio though myself as Zephyr *has* an async I/O framework already in it that closely matches io_uring called rtio as I've probably noted before.

2025-02-12 19:10 UTC, d3zd3z commented on zephyr/src/work.rs
> +    pub fn new() -> Result<Signal, Infallible> {
More about trying to maintain compatibility with other constructors, but realistically, it probably makes more sense to just have it return Self.

2025-02-12 19:12 UTC, d3zd3z commented on zephyr/src/work/futures.rs
> +    pub unsafe fn add_semaphore<'a>(&'a mut self, sem: &'a Semaphore) {
This has been rearranged, and these functions are now safe. The main safety concern with all of this is that these async methods can only be used with this executor. When I work to get another executor to be available, I'll try to address that.

2025-02-12 19:12 UTC, d3zd3z commented on zephyr/src/work/futures.rs
> +    pub unsafe fn add_signal<'a>(&'a mut self, signal: &'a Signal) {
Ditto, now safe.

2025-02-12 19:13 UTC, d3zd3z commented on zephyr/src/work/futures.rs
> +    pub unsafe fn add_queue<'a>(&'a mut self, queue: &'a Queue) {
Also now safe.

2025-02-13 13:59 UTC, jpeeters requested changes
Thank you so much for such addition to Rust bindings. I look forward to looking at the next steps.

I set this review as `request changes`, sorry I don't want to be rude, especially at one day of code freeze. Feel free to bypass this time if you need it.

2025-02-13 13:59 UTC, jpeeters commented on samples/work-philosophers/Cargo.toml
> +[profile.release]
Same as above about `codegen-units`.

2025-02-13 13:59 UTC, jpeeters commented on zephyr/Cargo.toml
> +arrayvec = { version = "0.7.6", default-features = false }
Is `arrayvec` better than containers in `heapless`? Or is it for a different use case?

2025-02-13 13:59 UTC, jpeeters commented on zephyr/src/kio.rs
> +pub fn spawn<F>(future: F, worker: &WorkQueue, name: &'static CStr) -> JoinHandle<F>
So as to limit coupling with C types, I think it is more relevant to use `&'static str` here. That being said, type coercion may occur in private functions.

2025-02-13 13:59 UTC, jpeeters commented on zephyr/src/kio.rs
> +pub fn spawn_local<F>(future: F, name: &'static CStr) -> JoinHandle<F>
Same here.

2025-02-13 13:59 UTC, jpeeters commented on zephyr/src/kio/sync.rs
> +pub struct Mutex<T: ?Sized> {
Sorry for my misunderstanding. What is the semantic difference with `zephyr::sync::Mutex`?

2025-02-13 13:59 UTC, jpeeters commented on zephyr/src/lib.rs
> +pub mod kio;
A general question: would it be possible to have a `no_alloc` version with `heapless` or do you think that wouldn't be relevant?

2025-02-13 13:59 UTC, jpeeters commented on zephyr/src/simpletls.rs
> +pub struct SimpleTls<T: Copy + Send> {
I understand the need for not too long name. Although, I think this could be helpful for the developer experience to have something more explicit like `SimpleLocalStorage`. Even more, we can agree that a simple implementation could be named `ThreadLocalStorage` and more advanced ones with specific names. In the end, if some developer prefer shorter names, they can alias to `Tls` internally in their project.

2025-02-13 13:59 UTC, jpeeters commented on zephyr/src/simpletls.rs
> +    data: AtomicPtr<Mutex<SimpleTls<T>>>,
I don't understand why we need an atomic on a `Sync` type like `Mutex` here. If this is because of the null possible value, maybe the type could be `Mutex<MaybeUninit<SimpleTls<T>>>` or something equivalent?

2025-02-13 14:48 UTC, d3zd3z commented on samples/bench/Cargo.toml
> +debug-assertions = true
I can give it a try.

2025-02-13 14:49 UTC, d3zd3z commented on samples/bench/src/basesem.rs
> +    pub fn new(initial_count: c_uint, limit: c_uint) -> Semaphore {
In this case, this was intended to just be a quick test to see if the "base sem" model will be workable. Given that this has similar performance to using `Fixed`, I will likely make a larger change across the codebase to have the zephyr objects directly, with an init atomic.  I won't be changing the APIs to the existing types.

2025-02-13 14:52 UTC, d3zd3z commented on samples/bench/src/basesem.rs
> +    fn get(&self) -> *mut k_sem {
The point of this little exercise (basesem, which will go away at some point) is to see about the feasibility of eliminating the `Fixed` type entirely. In this case, the items are always just used directly, and the atomic protects against things being moved (which only happens when there is a single reference anyway).

2025-02-13 14:54 UTC, d3zd3z commented on samples/bench/src/basesem.rs
> +    pub fn take(&self, timeout: impl Into<Timeout>) -> Result<()> {
At least for semaphores, I was trying to keep the same names as Zephyr. Embassy, for example, uses acquire and release. The very traditional names would be "try" and "increment", or even better, the Dutch "probeer" and "verhoog".

Names are always a little weird with semaphores because they tend to come from a specific way that semaphores are being used, whereas semaphores are actually pretty generic.

2025-02-13 14:57 UTC, d3zd3z commented on zephyr/src/kio.rs
> +pub fn spawn<F>(future: F, worker: &WorkQueue, name: &'static CStr) -> JoinHandle<F>
Honestly, I'm not quite sure what the best thing to do is. This `name` _must_ be null terminated, and must be static, so other than by leaking pointers or some kind of allocation, it has to be a CStr.

Realistically, I wonder if we should have the name stuff in here at all. I was hoping to be able to get the name passed through to SystemView, but it never ended up working, and otherwise, there isn't much purpose to it.

2025-02-13 14:58 UTC, d3zd3z commented on zephyr/src/kio/sync.rs
> +pub struct Mutex<T: ?Sized> {
Zephyr's Mutex type is only blocking, and using from async would block the entire work queue. This is kind of an interim solution to provide mutual exclusion (without condvar) that works from the workqueue-based async.

2025-02-13 14:59 UTC, d3zd3z commented on zephyr/src/lib.rs
> +pub mod kio;
I think it'd be a good idea, and a good thing, too, and a lot more reasonable to do after I get rid of `Fixed`. But, I think that is better to do as some changes to come after this.

2025-02-13 15:00 UTC, d3zd3z commented on zephyr/src/simpletls.rs
> +pub struct SimpleTls<T: Copy + Send> {
Perhaps `pub(crate)`? It really isn't intended for general consumption.

2025-02-13 15:01 UTC, d3zd3z commented on zephyr/src/simpletls.rs
> +    data: AtomicPtr<Mutex<SimpleTls<T>>>,
The problem is that currently, `Mutex` cannot be declared statically (the constructor is not const), as it requires an allocation. My proposal suggested in basesem will fix that.

2025-02-13 15:11 UTC, d3zd3z commented
> Thank you so much for such addition to Rust bindings. I look forward to hearing from you on the next steps.
> 
> I set this review as `request changes`, sorry I don't want to be rude, especially at one day of code freeze. Feel free to bypass this time if you need it.

Given the closeness to the feature freeze, I'm going to take the above as a kind of ok, to proceed with this, and make the changes in subsequent PRs. I think it will help to have this code in mainline for this release.

2025-02-13 15:11 UTC, merged